cart:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Velocity Controllers -----------------------------------------
  right_wheel_controller:
    type: effort_controllers/JointVelocityController
    joint: right_wheel_hinge
    pid: {p: 0.1, i: 0.01, d: 0.0}

  left_wheel_controller:
    type: effort_controllers/JointVelocityController
    joint: left_wheel_hinge
    pid: {p: 0.1, i: 0.01, d: 0.0}

