arm:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers -----------------------------------------
  post_controller:
    type: effort_controllers/JointPositionController
    joint: post_joint
    pid: {p: 100.0, i: 0.0, d: 0.0}

  elbow_1_controller:
    type: effort_controllers/JointPositionController
    joint: elbow_1_joint
    pid: {p: 100.0, i: 0.0, d: 0.0}

  elbow_2_controller:
    type: effort_controllers/JointPositionController
    joint: elbow_2_joint
    pid: {p: 100.0, i: 0.0, d: 0.0}


