rodrone:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Velocity Controllers -----------------------------------------
  pos_pos_rotor_joint_controller:
    type: effort_controllers/JointVelocityController
    joint: pos_pos_rotor_joint
    pid: {p: 100.0, i: 10.0, d: 0.01}

  neg_pos_rotor_joint_controller:
    type: effort_controllers/JointVelocityController
    joint: neg_pos_rotor_joint
    pid: {p: 100.0, i: 10.0, d: 0.01}

  neg_neg_rotor_joint_controller:
    type: effort_controllers/JointVelocityController
    joint: neg_neg_rotor_joint
    pid: {p: 100.0, i: 10.0, d: 0.01}

  pos_neg_rotor_joint_controller:
    type: effort_controllers/JointVelocityController
    joint: pos_neg_rotor_joint
    pid: {p: 100.0, i: 10.0, d: 0.01}
